{% set version = "0.9.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-markovchain
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/markovchain_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/markovchain/markovchain_{{ version }}.tar.gz
  sha256: eef926d660dbd54362551b7fff64a9f2ac284f1f87bfe07cdffc99632489c77c
  
build:
  merge_build_host: true  # [win]
  skip: true              # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix >=1.5.0
    - r-rcpp >=1.0.2
    - r-rcpparmadillo >=0.9.600.4.0
    - r-rcppparallel
    - r-expm
    - r-igraph
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix >=1.5.0
    - r-rcpp >=1.0.2
    - r-rcpparmadillo >=0.9.600.4.0
    - r-rcppparallel
    - r-expm
    - r-igraph

test:
  requires:
    - r-testthat
  source_files:
    - tests/testthat/
    - tests/testthat.R
  commands:
    - $R -e "library('markovchain')"                                                  # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('markovchain')\""                                         # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://github.com/spedygiorgio/markovchain/
  license: MIT
  summary: Functions and S4 methods to create and manage discrete time Markov chains more easily. In addition functions to perform statistical (fitting and drawing random variates) and probabilistic (analysis of their structural proprieties) analysis are provided.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
