{% set version = "0.8.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-markovchain
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/markovchain_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/markovchain/markovchain_{{ version }}.tar.gz
  sha256: 2f1d763c2cd953a3a07439455c2d731b3279904e125373e6e794d59e26cf13b7

build:
  merge_build_host: True  # [win]
  skip: True  # [r_base == "3.5.1"]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=1.0.2
    - r-rcpparmadillo >=0.9.600.4.0
    - r-rcppparallel
    - r-expm
    - r-igraph
    - r-matlab
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=1.0.2
    - r-rcpparmadillo >=0.9.600.4.0
    - r-rcppparallel
    - r-expm
    - r-igraph
    - r-matlab

test:
  commands:
    - $R -e "library('markovchain')"           # [not win]
    - "\"%R%\" -e \"library('markovchain')\""  # [win]

about:
  home: http://github.com/spedygiorgio/markovchain/
  license: GPL-2
  summary: Functions and S4 methods to create and manage discrete time Markov chains more easily.
    In addition functions to perform statistical (fitting and drawing random variates)
    and probabilistic (analysis of their structural proprieties) analysis are provided.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: markovchain
# Type: Package
# Title: Easy Handling Discrete Time Markov Chains
# Version: 0.8.0
# Date: 2019-09-13
# Authors@R: c( person("Giorgio Alfredo", "Spedicato", role = c("aut", "cre"), email = "spedicato_giorgio@yahoo.it",comment = c(ORCID = "0000-0002-0315-8888")), person("Tae", "Seung Kang", role = "aut"), person("Sai", "Bhargav Yalamanchi", role = "aut"), person("Mildenberger", "Thoralf", role = "ctb", comment = c(ORCID = "0000-0001-7242-1873")), person("Deepak", "Yadav", role = "aut"), person("Ignacio", "Cordon", role = "aut", comment = c(ORCID = "0000-0002-3152-0231")), person("Vandit", "Jain", role = "ctb"), person("Toni", "Giorgino", role="ctb", comment = c(ORCID = "0000-0001-6449-0596")) )
# Maintainer: Giorgio Alfredo Spedicato <spedicato_giorgio@yahoo.it>
# Description: Functions and S4 methods to create and manage discrete time Markov chains more easily. In addition functions to perform statistical (fitting and drawing random variates) and probabilistic (analysis of their structural proprieties) analysis are provided.
# License: GPL-2
# Depends: R (>= 3.5.0), methods
# Imports: igraph, Matrix, matlab, expm, stats4, parallel, Rcpp (>= 1.0.2), RcppParallel, utils, stats, grDevices
# Suggests: knitr, testthat, diagram, DiagrammeR, msm, etm, Rsolnp, knitcitations, rmarkdown, ctmcd, MmgraphR, bookdown, rticles
# VignetteBuilder: utils, knitr
# LinkingTo: Rcpp, RcppParallel, RcppArmadillo (>= 0.9.600.4.0)
# SystemRequirements: GNU make
# LazyLoad: yes
# ByteCompile: yes
# Encoding: UTF-8
# BugReports: http://github.com/spedygiorgio/markovchain/issues
# URL: http://github.com/spedygiorgio/markovchain/
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-09-13 18:42:42 UTC; giorg
# Author: Giorgio Alfredo Spedicato [aut, cre] (<https://orcid.org/0000-0002-0315-8888>), Tae Seung Kang [aut], Sai Bhargav Yalamanchi [aut], Mildenberger Thoralf [ctb] (<https://orcid.org/0000-0001-7242-1873>), Deepak Yadav [aut], Ignacio Cordon [aut] (<https://orcid.org/0000-0002-3152-0231>), Vandit Jain [ctb], Toni Giorgino [ctb] (<https://orcid.org/0000-0001-6449-0596>)
# Repository: CRAN
# Date/Publication: 2019-09-14 21:30:08 UTC
