appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: HgvNM9aaFEh8uiEFOOxhpz/rUGsj18hpte1UwLYQI8XynyfBpFI/Y3wkSlUpi+seu4W0waI0Rzz3shA/WlOuQRbuLF8VvyvaHXTCEWxX3Wjze3JC0EwBIT47hWH69WKlLF6Jqc9Kw7oTXhkA32tMJQGQ2B6q7vP/HWNBaUnXXRhcdcUE5TBOnO3DS3YI5w9e47fL89k3CkMDKq6UZO2w5Jl0OHrqdBZTOxtHTXKJeAVrW+EoSJFuu1F/aPugLLSZMrBvpQ2BfqcBeEOuWP4ov5nR0FfurDMK7Lzhaw4GOliWmM/Wj6HJOAoVgDpVrMZoxeI8u85vzYzxz3zisavFhuUzcPeqmIjhfhjIF5uyfu9l7gt7oo+IEzLdDwBIny9UyMY6NM3BoLSdPUAYywU2lrL36PRb+P8p00ZbInh+EzKm2YlQ71qGLj7h4JMskWkrBjYGDMyFwZyEl3XSqLq29p4GXRLbsDxqSp/VR4fL9dnXmFW+58ivrAv3IAyFjBFobJtYQ/7ycbNTZlmtt5eIV7Eav0IXWWL07XFUY5QPUcJ+wex/0VGTVDPpPGR4WP+LAK6W1jS7fxThLdGJq3TOjVtUh66rKluLtJ6y3C3DzoCF3tTD/D8x99Zotf8L8FRMdwoOdqPXNc4B/chYaf/X7p5NqfagfIU32Gqop3XG5eQ=
conda_forge_output_validation: true
