travis:
  secure:
    BINSTAR_TOKEN: E3djL7lscdKI3BC6+iMThBFja3BXJL5owU9LJNhQRyBvuftcwCQGA+gyeD+WoSF/t/lFLeJPQQdH71knLdsQ0M0itQwK71BgDLfGOfjhwDZIu1tdT/uoPZDoa/4FL1IPMKDHDjOLGU5vpa4ft5g1VRZGdL193SOsQfaXGEtdFKD+HScT1DNsa06UovOji6/h7CfpSriCCY4CfO/uVPyLYwNaEFm9BU7zqdU/qwly0/4pYxhql9hYMOya5FBj5mvihCwpFSCKe4M8lL/05/TiXEO2eaJ5QWf5+NiZfVh8h58dOHrebt6pd0zyxShiqoK87VGT4/tlkLHSwoozyS7Y36WR29ZDCVdUdA3J2Q7tLsoncb2yGYdu3FsixlpnyhYdJKkEXKOBEDW53fJ8IkaoNDCQ0tNJZApRBH0Znj7iqySKbQaGkjqNcuw5sQflgEHApgRJYt3AFEG7al8rjtoEVcIi4ZY7uNA9FO14tniSsus3xbncOqgJdu5qoJZcz2wERTFMo2CI5YFLJJg92o6E/q1s5yEvG6ugOKfbKhtVSN7rwFMkelQ2ROSV3imM5Hr8FBpJO744PDhyJrY76MGvOwTed0L3jcyj0WjShMJQEJI8yY79mc+jBTnInAx0OYd2y8WEapReAVhDDG+H3uuUHflfyzY8U6Hhhf39aa7Lhu0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
